# Generated by Django 3.1.7 on 2021-02-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210226_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee_size',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
