# Generated by Django 3.1.7 on 2021-02-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_employee_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_size',
            field=models.PositiveIntegerField(),
        ),
    ]
